import { prefix } from "./variables.js"

export const articles = {
  "Featured Art": [
    {
      "title": "Self-portrait by Frida Kahlo",
      "sub-title": "",
      "author": "Frida Kahlo",
      "description":[
          "Frida Kahlo, born Magdalena Carmen Frida Kahlo y Calderón; 6 July 1907 – 13 July 1954) was a Mexican painter known for her many portraits, self-portraits, and works inspired by the nature and artifacts of Mexico. Inspired by the country's popular culture, she employed a naïve folk art style to explore questions of identity, postcolonialism, gender, class, and race in Mexican society. Her paintings often had strong autobiographical elements and mixed realism with fantasy. In addition to belonging to the post-revolutionary Mexicayotl movement, which sought to define a Mexican identity, Kahlo has been described as a surrealist or magical realist.",
          "Born to a German father and a mestiza mother, Kahlo spent most of her childhood and adult life at La Casa Azul, her family home in Coyoacán, now publicly accessible as the Frida Kahlo Museum. Although she was disabled by polio as a child, Kahlo had been a promising student headed for medical school until a traffic accident at age eighteen, which caused her lifelong pain and medical problems. During her recovery, she returned to her childhood hobby of art with the idea of becoming an artist.",
          "Kahlo's interests in politics and art led to her joining the Mexican Communist Party in 1927, through which she met fellow Mexican artist Diego Rivera. The couple married in 1928, and spent the late 1920s and early 1930s travelling in Mexico and the United States together. During this time, she developed her artistic style, drew her main inspiration from Mexican folk culture, and painted mostly small self-portraits which mixed elements from pre-Columbian and Catholic beliefs. Her paintings raised the interest of Surrealist artist André Breton, who arranged for Kahlo's first solo exhibition at the Julien Levy Gallery in New York in 1938.",
          "<a style=\"font-weight:bold\" href=\"https://southerncrossreview.org/127/frida-letter-eng.html\">Continue reading...</a>",
      ],
      "imgUrl": `${prefix}frida-1.jpg`,
      "link": `javascript:void(0)`,
      "poem": false,
      "mainImg": true,
    },
   ],
  "Education": [
    {
      "title": "Education as a Social Question",
      "sub-title": "Lecture 2",
      "author": "by Rudolf Steiner",
      "description":[
          "If we wish to understand the task of anthroposophical spiritual science in the present and immediate future we must consider the character of mankind's evolution since the middle of the fifteenth century. Everything that happens now depends on the fact that since that time there lives in mankind the impulse for each single individuality to attain the pinnacle of personality, to become a whole personality. This was not possible, nor was it the task of mankind in earlier epochs of our post-Atlantean evolution. If we want to understand this great change in the middle of which we find ourselves, we must focus our attention still more precisely upon such matters as I characterized yesterday.",
          "I said that in our spiritual life we still have a Greek constitution of soul. The way we form our thoughts, the manner in which we are accustomed to think about the world, is an echo of the Greek mind. And the way we are accustomed to look at civic rights and everything connected with them is an echo of the Roman mentality. In the State we still see the structure as it existed in the Roman Empire. Only if people will realize that the impulse of the threefold society must enter our chaotic present will there be clarity in thinking and willing.",
      ],
      "imgUrl": `${prefix}waldirf-class.jpg`,
      "link": `${prefix}education-social-question-2.html`,
      "poem": false,
      "mainImg": false,
    },
   ],
  "Social Science": [
    {
      "title": "Favela Children",
      "sub-title": "Chapter 3",
      "author": "by Ute Creamer",
      "description":[
        "<span style=\"font-weight:bold\">Londrina, October 14</span>",
        "This evening I was again with the old Macumba priestess, Dona Jacinta. She is of imposing appearance, vital, strong, tolerant and unwavering. One can imagine that she would be honored in heathen Africa as a symbol of the Earth Mother. You feel well in her presence, she exudes calmness.",
        "She led me into her Macumba-room. On one side are wooden benches, in the opposite corner stands her altar with its countless holy figures. Many gods have Christian as well as heathen names. For example St. George is Ogún, the god of war in the African religion. St. Michael corresponds to Xangó, the god of thunder and lightning. Yemanjá, the sea-goddess, is the Virgin Mary. Exú is the Devil and Oxalá, the god of life and fertility, corresponds to Jesus and the Holy Spirit."
      ],
      "imgUrl": `${prefix}favela-cover.jpg`,
      "link": `${prefix}favela-children-3.html`,
      "poem": false,
      "mainImg": false,
    },
   ],
  "Political Science": [
    {
      "title": "Can the Military-Industrial Complex Be Tamed?",
      "sub-title": "Cutting the Pentagon Budget in Half Would Finally Force the Generals to Think",
      "author": "WILLIAM J ASTORE",
      "description":[
        "My name is Bill Astore and I’m a card-carrying member of the military-industrial complex (MIC).",
        "Sure, I hung up my military uniform for the last time in 2005. Since 2007, I’ve been writing articles for TomDispatch focused largely on critiquing that same MIC and America’s permanent war economy. I’ve written against this country’s wasteful and unwise wars in Iraq and Afghanistan, its costly and disastrous weapons systems, and its undemocratic embrace of warriors and militarism. Nevertheless, I remain a lieutenant colonel, if a retired one. I still have my military ID card, if only to get on bases, and I still tend to say “we” when I talk about my fellow soldiers, Marines, sailors, and airmen (and our “guardians,” too, now that we have a Space Force).",
        "So, when I talk to organizations that are antiwar, that seek to downsize, dismantle, or otherwise weaken the MIC, I’m upfront about my military biases even as I add my own voice to their critiques. Of course, you don’t have to be antiwar to be highly suspicious of the U.S. military. Senior leaders in “my” military have lied so often, whether in the Vietnam War era of the last century or in this one about “progress” in Iraq and Afghanistan, that you’d have to be asleep at the wheel or ignorant not to have suspected the official story.",
      ],
      "imgUrl": `${prefix}military-industrial-complex.png`,
      "link": `${prefix}astore-m-i-complex.html`,
      "poem": false,
      "mainImg": false,
    },
    {
      "title": "Nuclear Fusion Won’t Save the Climate",
      "sub-title": "But It Might Blow Up the World",
      "author": "JOSHUA FRANK",
      "description":[
        "I awoke on December 13th to news about what could be the most significant scientific breakthrough since the Food and Drug Administration authorized the first Covid vaccine for emergency use two years ago. This time, however, the achievement had nothing to do with that ongoing public health crisis. Instead, as the New York Times and CNN alerted me that morning, at stake was a new technology that could potentially solve the worst dilemma humanity faces: climate change and the desperate overheating of our planet. Net-energy-gain fusion, a long-sought-after panacea for all that’s wrong with traditional nuclear-fission energy (read: accidents, radioactive waste), had finally been achieved at the Lawrence Livermore National Laboratory in California.",
        "“This is such a wonderful example of a possibility realized, a scientific milestone achieved, and a road ahead to the possibilities for clean energy,” exclaimed White House science adviser Arati Prabhakar.",
      ],
      "imgUrl": `${prefix}atomic-blast.jpeg`,
      "link": `${prefix}frank-fusion.html`,
      "poem": false,
      "mainImg": false,
    },
    {
      "title": "American Exceptionalism on Full Display",
      "sub-title": "Why This Country Might Want to Lower Its Expectations",
      "author": "Rebecca Gordon",
      "description":[
        "Let me start with a confession: I no longer read all the way through newspaper stories about the war in Ukraine. After years of writing about war and torture, I’ve reached my limit. These days, I just can’t pore through the details of the ongoing nightmare there. It’s shameful, but I don’t want to know the names of the dead or examine images caught by brave photographers of half-exploded buildings, exposing details — a shoe, a chair, a doll, some half-destroyed possessions — of lives lost, while I remain safe and warm in San Francisco. Increasingly, I find that I just can’t bear it.",
        "And so I scan the headlines and the opening paragraphs, picking up just enough to grasp the shape of Vladimir Putin’s horrific military strategy: the bombing of civilian targets like markets and apartment buildings, the attacks on the civilian power grid, and the outright murder of the residents of cities and towns occupied by Russian troops. And these aren’t aberrations in an otherwise lawfully conducted war. No, they represent an intentional strategy of terror, designed to demoralize civilians rather than to defeat an enemy military. This means, of course, that they’re also war crimes: violations of the laws and customs of war as summarized in 2005 by the International Committee of the Red Cross (ICRC).",
        "The first rule of war, as laid out by the ICRC, requires combatant countries to distinguish between (permitted) military and (prohibited) civilian targets. The second states that “acts or threats of violence the primary purpose of which is to spread terror among the civilian population” — an all-too-on-target summary of Russia’s war-making these last 10 months — “are prohibited.” Violating that prohibition is a crime.,"
      ],
      "imgUrl": `${prefix}exceptionalism.webp`,
      "link": `${prefix}gordon-exceptional.html`,
      "poem": false,
      "mainImg": false,
    },
   ],
  "Anthroposophy": [
    {
      "title": "The Gospel of John in Relation to the Other Three Gospels",
      "sub-title": "Lecture One of Fourteen - The Johannine Christians",
      "author": "Rudolf Steiner",
      "description":[
        "My dear Friends:",
        "A special festival has long been celebrated on this particular day of the year by a great number of those seeking higher wisdom; and many friends of our anthroposophical movement here in this city have wished this series of lectures to commence on this day, St. John's Day.",
        "The day of the year bearing this name was a festival as far back as the time of ancient Persia. There, on a day corresponding to a June day as we know it, the so-called Festival of the Baptism by Water and Fire was celebrated. In ancient Rome the Festival of Vesta was held on a similar day in June, and that again was a festival of baptism by fire. Going back to the time of pre-Christian culture in Europe and including the period before Christianity had become widely disseminated, we find a similar June festival coinciding with the time when the days are longest and the nights shortest, when the days start to become shorter again, when the sun once more begins to lose some of the power that provides for all earthly growth and thriving. This June festival seemed to our European forefathers like a retrogression, a gradual evanescence, of the God Baldur who was thought of as associated with the sun. Then in Christian times this June festival gradually became the Festival of St. John in memory of the Forerunner of the Christ Jesus. In this way it can form the starting point, as it were, for our discussions during the coming days of that most significant event in human evolution which we call the deed of the Christ Jesus. This deed, its whole significance for the development of mankind, the way it is revealed primarily in the most important Christian document, the Gospel of St. John — and then a comparison of this with the other Gospels — a study of all this will form the subject of this lecture cycle.",
      ],
      "imgUrl": `${prefix}rose-cross.jpg`,
      "link": `${prefix}gospel-john-1.html`,
      "poem": false,
      "mainImg": false,
    },
    {
      "title": "Course on World Economy",
      "sub-title": "Lecture 1",
      "author": "Rudolf Steiner",
      "description":[
        "Ladies and Gentlemen,",
        "Today I intend a kind of introduction. In tomorrow's lecture we shall begin and try to give a more or less complete picture of the questions of social and political economy which man today must set before himself.",
        "The subject of Economics, as we speak of it today, is in reality a very recent creation. It did not arise until the time when the economic life of modern peoples had become extraordinarily complicated in comparison with earlier conditions. As this Course is intended primarily for students of Political Economy, it is necessary by way of introduction to point out this peculiarity of the economic thinking of today.",
      ],
      "imgUrl": `${prefix}steiner-economy-1.jpg`,
      "link": `${prefix}steiner-economy-1.html`,
      "poem": false,
      "mainImg": false,
    },
   ],
  "Biology and Evolution": [
    {
      "title": "Evolution as it was meant to be",
      "sub-title": "How the World Lends Itself to Our Knowing",
      "author": "Stephen L. Talbott",
      "description":[
        "All physical scientists, in an effort to understand reality, take their stand upon a tiny island of knowledge, surrounded by an immense, fathomless sea of ignorance. The island is forever threatened and re-shaped by revelatory eruptions from the surrounding deep.",
        "According to the celebrated physicist, Richard Feynman, \"we have no knowledge of what energy is\" (Feynman et al. 1963). Nor, for that matter, do we know what a force is. And the same is true of all the foundational terms of physics. Matter, the supposedly solid ground of material reality, remains an enigma that has only grown more perplexing along with advances in quantum physics. Other basic terms such as “space”, “time”, and “field” — while perfectly workable as conceptual black boxes in the context of the physicist’s narrow mathematical aspirations — are not themselves so much elements of adequate explanation as they are perplexities in need of explanation.",
      ],
      "imgUrl": `${prefix}nature.gif`,
      "link": `https://bwo.life/bk/epist2.htm`,
      "poem": false,
      "mainImg": false,
    },
   ],
  "Fiction": [
    {
      "title": "The Intelligence Analyst",
      "sub-title": "",
      "author": "Frank Thomas Smith",
      "description":[
        "Roberto Fox was kicked out of Military Intelligence unceremoniously, and he wanted to know why. I was reminded of Roberto's story when reading about and sympathizing with Bradley Manning, that private-first-class who sent all the so-called “secret” information to WikiLeaks. I was reminded of how stupid, that's the best word for it, but one could also say inept, bureaucratic, clumsy and a whole list of adjectives from the thesaurus to describe the United States Army – or, probably, any army. It's just that my experience is with the American version. Just think: a private-first-class sitting in front of a computer somewhere in the desert in Iraq with access to the electronic messages sent from embassies all over the world to the State Department in Washington. Note, however, that Manning is an “intelligence analyst”. Why does he have such an important sounding MOS (Military Occupation Specialty) and still be only a Pfc? It's because he's intelligent and maybe he knows a foreign language, it doesn't matter which one; the path to being an intelligence analyst is to know a foreign language. They give you IQ tests when you enter the army, and if your IQ is higher than a baboon's they call you out of formation for duty as something cooler than an infantry grunt.",
        "What I'm about to tell you happened to Roberto Fox when there was still a draft and therefore much smarter people were in the service; in fact draftees were often so much more intelligent than officers that it was embarrassing. I could tell you some anecdotes to prove it, but now isn't the time. Maybe later, or in another life.",
      ],
      "imgUrl": `${prefix}spy.jpg`,
      "link": `${prefix}fts-analyst.html`,
      "poem": false,
      "mainImg": false,
    },
    {
      "title": "Love in the Life of Spies",
      "sub-title": "Foreword",
      "author": "by Frank Thomas Smith",
      "description":[
        "<span style=\"font-weight:bold\">Florida, Buenos Aires, Argentina</span>",
        "Cerrado read the sign hanging slightly askew inside the upper glass part of Die Glocke’s door. What the hell, Jacks thought, it’s lunch time, how can they be closed. Something’s wrong. He peered through the glass and saw the old waiter sitting alone at a table reading the Freie Presse, a fascist German-language daily. He knocked on the window. The waiter looked up, startled and stared wide-eyed at the door. When he recognized Marvin Jacks he put down the paper, smiled, stood up heavily and opened the door after unlocking it.",
        "“You called for a reservation,” he said in German, “nicht wahr?”",
        "Jacks nodded. “Why is the restaurant closed? Has something happened?”",
      ],
      "imgUrl": `${prefix}love-spies.jpg`,
      "link": `${prefix}love-life-spies-forward.html`,
      "poem": false,
      "mainImg": false,
    },
    {
      "title": "A Streetcar Named Karma",
      "sub-title": "",
      "author": "by Frank Thomas Smith",
      "description":[
        "A lecture wasn't exactly what I had in mind for the evening, but there we were, Katrina and I, approaching the hall where it was to take place. A full moon shone into the narrow cobblestoned street. Its presence more or less guaranteed that there would be no more snow that night.",
        "That same day, I think it was early afternoon, I had boarded a streetcar and found a spot among the standees, when the clasp on my briefcase somehow opened as we rounded a sharp curve and the books and papers tumbled out. I bent to retrieve them and fell against another standee, knocking her over and falling almost on top of her. I stammered apologies in German, my native tongue, instead of Czech. My reaction was automatic, but the fact is that in that enlightened age all educated people in Prague spoke German. Hers was lightly accented. She helped me pick up my things, which were strewn around and soiled by the slush the passengers' shoes had tracked into the car. An elderly couple vacated a double seat at the next stop and I quickly grasped the hand-guard and invited her to sit next to the window. I took my place next to her on the aisle. She wasn't a beautiful woman, at least not in the usual sense. You could have called her attractive though. Her most salient feature was her smile, wide and spontaneous, lighting up her face. Though she wore a heavy fur coat against the cold, I could tell that she was somewhat plump, which was to my taste.",
      ],
      "imgUrl": `${prefix}streetcar-small.jpg`,
      "link": `${prefix}streetcar-karma.html`,
      "poem": false,
      "mainImg": false,
    },
    {
      "title": "Dear Dhriti",
      "sub-title": "",
      "author": "by S.F.Wright",
      "description":[
        "Dear Dhriti,",
        "I am writing, as a colleague and as a friend, to ask you to return to Voragine High School.",
        "I understand why you left—or why you felt that you had to leave. But, Dhriti, you must consider the fact that the world changes and that we must adapt to its changes. Long ago, schools were gender segregated. Now, almost all schools are coeducational. For years, teachers taught with pencils and notebooks. Today, we use computers and Google Docs. Once upon a time, the idea of teachers’ carrying firearms in school was not only absurd but inconceivable. As of recently, we teachers are required to be armed during working hours.",
        "As with the other policies, we are adjusting to this new one. And I know that if you gave it a little time, Dhriti, you would adjust to this change as well.",
      ],
      "imgUrl": `${prefix}armed-teacher.jpg`,
      "link": `${prefix}wright-dhriti.html`,
      "poem": false,
      "mainImg": false,
    },
   ],
  "Children's Corner": [
    {
      "title": "The Magic Mound",
      "sub-title": "Chapter 4 - Vitaluz, the Youth Potion",
      "author": "Frank Thomas Smith",
      "description":[
        "A girl dressed like Mara came through the palace's front gate and walked towards them. She was smiling and had her hands stretched out in a gesture which obviously meant welcome. Sergio and Divino thought she must be Mara's sister because they looked so much alike they could have been twins.",
        "\"This is Sergio and the little one is Divino,\" Mara told her.",
        "\"What lovely names!\" she said in a voice somewhat deeper than Mara's. Sergio was pleased that not only Divino's name had been praised.",
        "\"Come.\" She put her arms around the boys' shoulders and led them into the palace grounds.",
        "\"Are we going to meet Queen Mamara now?\" Divino asked her.",
      ],
      "imgUrl": `${prefix}mound-map.jpg`,
      "link": `${prefix}magic-mound-4.html`,
      "poem": false,
      "mainImg": false,
    },
    {
      "title": "Journey to the Stars",
      "sub-title": "",
      "author": "Frank Thomas Smith",
      "description":[
        "One evening Nicky and his little sister Caroline were sitting in the meadow near their home at the edge of the forest. The sky overhead was like a cape of black silk encrusted with brilliant jewels.",
        "\“How many stars are there in the sky, Nicky\”, Caroline asked.",
        "“A lot.”",
        "“Yes, I can see that, but how many?” she insisted.",
        "“Billions. Nobody knows.”",
        "“Let’s count them.”",
        "Nicky laughed. “Fine, you count them and tell me how many there are.”",
      ],
      "imgUrl": `https://southerncrossreview.org/149/journey-to-stars.jpg`,
      "link": `https://southerncrossreview.org/149/journey-to-stars.html`,
      "poem": false,
      "mainImg": false,
    },
   ],
  "Spiritual Science": [
    {
      "title": "Intergalactic Reincarnation",
      "sub-title": "",
      "author": "by Frank Thomas Smith",
      "description":[
        "Beyond the highest, Aconcagua's peak,<br>Lives a lady of fragile health,<br>Known by the name Mireya.",
        "Her glance, her smile are all I seek,<br>Are more to me than worlds of wealth,<br>The ailing lady, Mireya.",
        "Her steps are slower now, embraces weak,<br>So I will pray for her in stealth,<br>For the life of my love Mireya.",
      ],
      "imgUrl": `${prefix}intergalactic.jpg`,
      "link": `${prefix}mireya-intergalactic.html`,
      "poem": true,
      "mainImg": false,
    },
   ],
}
