import { prefix } from "./variables.js"

export const articles = {
  "Book Review": [
    {
      "title": "Book Review - JFK and the Unspeakable",
      "sub-title": "",
      "author": "James W. Douglass",
      "description":[
        "Do you remember where you were when President Kennedy was killed? I do.",
        "I was in a cafe on a street in downtown Buenos Aires. It was a warm southern hemisphere spring day and I was waiting for a colleague who should have arrived a few minutes ago; but this being Argentina, where punctuality is a mere theoretical virtue, I was accustomed to waiting. There was a buzz of voices in the rear of the café that seemed to be creeping nearer and louder.",
        "Suddenly Osvaldo rushed in. He didn't stop to even say Buenos Días. “Did you hear that Kennedy has been shot?” he blurted out.",
        "“Kennedy?” I repeated stupidly.",
      ],
      "imgUrl": `${prefix}jfk-assassination-2.png`,
      "link": `${prefix}jfk-review.html`,
      "poem": false,
      "mainImg": false,
    },
    {
      "title": "Beyond Belief",
      "sub-title": "",
      "author": "Elaine Pagels",
      "description":[
        "Elaine Pagels, professor of religion at Princeton University, became famous – well, at least well known – with the publication of her book, The Gnostic Gospels, in 1979. She has written several other books as well on the history of Christianity, establishing her as the foremost popular scholar in the field.",
        "Beyond Belief, published in 2003 by Random House, is a sort of sequel to The Gnostic Gospels, in that it incorporates the new scholarship that has come to light since that book was published. Since Ms. Pagels’ infant son was diagnosed with fatal pulmonary hypertension, her pursuit of knowledge about who Jesus really was has become a question of personal urgency for her. This need is reflected in the text and transforms the book into much more than a scholarly treatise for the curious. She wants to know what Christ meant to his followers before doctrine and dogmas, in other words, before Christianity was re-invented by the Roman Catholic Church.",
      ],
      "imgUrl": `${prefix}thomas-apostle.jpg`,
      "link": `${prefix}pagels-beyond-belief.html`,
      "poem": false,
      "mainImg": false,
    },
   ],
  "Fiction": [
    {
      "title": "“We are the lucky ones…”",
      "sub-title": "(Bilingual)",
      "author": "Z",
      "description":[
        "When I moved with my family to the country from Buenos Aires 14 years ago, we lived in an old house, once the core building of an estancia. There were ten acres of what was once farmland, but had turned into what my son, ten years old at the time, rather romantically and with his flair for exaggeration called a jungle. After a few days of snooping around in the “jungle” with his dog, he found a rusty old lunch pail. It had no lock on it, but it was rusted tightly shut, so he brought it to me to open, which I did with the help of a chisel and hammer. Instead of a rotted chicken leg, we found a…what should I call it? An essay, or simply an unfinished manuscript. Translated into English, it reads as follows.",
        "We were four or five men, all about the same age, in our early forties, except for Dr. Bernard Lievegoed, who was in his mid-sixties then, and Lex Bos, seven years older than I. We were of different nationalities – I remember a Swiss who lived in Sao Paulo, Brazil, a German who lived in Johannesburg, South Africa. The others were Europeans, if I remember correctly. And I, an Argentine who was about to escape from my own country to Spain. Lievegoed and Bos were Dutch and we were in the Dutch city of Zeist, at the headquarters of NPI – the Netherlands Pedagogic Institute.",
      ],
      "imgUrl": `${prefix}boy-and-dog.jpg`,
      "link": `${prefix}anthrobio.html`,
      "poem": false,
      "mainImg": false,
    },
    {
      "title": "Blonde Noir",
      "sub-title": "",
      "author": "DC Diamondopolous",
      "description":[
        "Kit Covington sat on the sofa in her Pacific Palisades mansion with a cigarette lodged in the side of her mouth. A cloud of smoke floated around her head. She adjusted the oxygen tube in her nose, then brushed ash from her dog Muffin’s champagne-colored curls. The miniature poodle dozing in Kit’s lap startled when the camera crew from The Great Morning Talk Show banged equipment into Kit’s antique furniture.",
        "“Watch it! You scratch anything, you’ll pay for the restoration.” Since her left lung had been removed, Kit’s husky voice had a rattle that lingered between words chaining them together like loose ball bearings.",
        "“Sorry,” the stocky, tattooed sound woman said.",
        "Kit wondered if the all-female crew was a set-up—some kind of knife-twisting in the gut. She’d been anxious about the interview and now regretted it.",
      ],
      "imgUrl": `${prefix}woman_kooning.webp`,
      "link": `${prefix}blonde-noir.html`,
      "poem": false,
      "mainImg": false,
    },
    {
      "title": "They Call Me Jackie Robinson in Brazil",
      "sub-title": "",
      "author": "Frank Thomas Smith",
      "description":[
        "It's Jackie Robinson Day! All the major league baseball team players have his number – 42 – on their backs. Well, why not? Jackie was not only one of the best baseball players who ever lived, he was, more importantly, the first African American (called Negro back then) to play in the Major Leagues, for the Brooklyn Dodgers. He took a lot of racist insults – not in Brooklyn, in the South – which he knew he would, but never blew his top. It's not a national holiday yet, but somehow better.",
        "As I watched the ceremony honoring his memory on TV, another personal memory came to mind: why they call me Jackie Robinson in Brazil.",
      ],
      "imgUrl": `${prefix}jackie-42.jpg`,
      "link": `${prefix}fts-jackie-robinson-brasil.html`,
      "poem": false,
      "mainImg": false,
    },
    {
      "title": "Saint Death",
      "sub-title": "(Bilingual)",
      "author": "Frank Thomas Smith",
      "description":[
        "I had a pounding hangover when I woke up well past noon in a strange bed. A bottle of mineral water and an empty glass stood on the night table and clean towels had been placed on the dresser. I got up slowly, drank two glasses of water, opened the shutters and looked out the window. The bright sky that met the flat grassy earth at the horizon assaulted my aching eyes. After a shower and two aspirins that I found in the bathroom medicine cabinet, I eased myself downstairs to where the Prietos were having lunch in the dining room. Both were in their early sixties, Señora Prieto perhaps a few years younger. She tinkled a small bell and an obese Indian woman entered silently from the kitchen. I gladly accepted Señora Prieto’s suggestion of breakfast of café con leche, toast and marmalade. The servant waddled back to the kitchen.",
        "“Our son Pedro did not give us any details concerning your problem and we would not dream of asking you,” Señora Prieto said. “We can only offer you our hospitality and hope that your stay here will provide the tranquility you seek.” She was very polite and obviously sincere, but her smile seemed forced. My colleague Pedro Prieto had insisted that I go to the Chaco and spend some time on his parent’s estancia when, according to him, I was on the point of cracking up over a woman. It’s true that I was in pretty bad shape, drinking too much and all that, but…no point in getting ahead of myself.",
      ],
      "imgUrl": `${prefix}san-la-muerte-1.jpg`,
      "link": `${prefix}fts-saint-death.html`,
      "poem": false,
      "mainImg": false,
    },
    {
      "title": "Love In The Life Of Spies",
      "sub-title": "",
      "author": "Frank Thomas Smith",
      "description":[
        "That night I went to the Gilded Cage with a purpose and was dressed accordingly: blue sports jacket, slacks, loafers without socks, white shirt open to the third button. I arrived early and found a stool at the semi-circular bar, put a fiver on the bar for effect, ordered a Millers High Life, lit a cigarette, and looked around. The bar-stools were almost all occupied – by men. Soon they'd be three deep, it being Friday night. The piano was set back in an alcove to the left-rear of the bar. It also had bar-stools around it so you could drink there and look at the player with one elbow on the piano. Two young couples were perched on the stools, the men in suits and ties and the giggly women showing a lot of leg. The men were probably asshole officers from Fort Ord, I figured. The piano player was playing As Time Goes By, probably requested by one of the girls. That kind of girl always requested that kind of song because they liked to think of themselves as Ingrid Bergman - romantic and teary - without realizing that it wasn't a song you could request, it had to hit you out of the blue. I lit another cigarette and nursed my beer.",
      ],
      "imgUrl": `${prefix}love-life-cover.jpg`,
      "link": `${prefix}love-life-5.html`,
      "poem": false,
      "mainImg": false,
    },
   ],
  "Social Science": [
    {
      "title": "Favela Children - Chapter 6 & 7",
      "sub-title": "",
      "author": "Ute Creamer",
      "description":[
        "Once upon a time there was a coral-colored serpent and a little black girl. She lived in the middle of a dense jungle. The trees grew so high and the undergrowth was so thick that the way had to be hacked out with a bush-knife, after which the jungle closed in again. The strength of the sun and the sap of the earth were so strong that every trampled blade of grass and every cut-off branch grew back almost immediately. Wild animals, tigers, serpents, armadillos, monkeys and parrots inhabited the jungle; crocodiles lounged lazily in a wide muddy stream that wandered slowly to the sea.",
        "Talinha, the black child, lived in this jungle. Her other had died at her birth. As the angel descended to carry her mother to heaven, she spread her wings over the new-born child, which made her invisible to human eyes. Even her father could no longer see his daughter. Sad because he lost his wife and daughter on the same day, he left his house and the jungle for good in order to live in a place where there were more people. Talinha, small and defenseless against the threatening jungle, stayed behind.",
      ],
      "imgUrl": `${prefix}favela-cover.jpg`,
      "link": `${prefix}favela-children-6-7.html`,
      "poem": false,
      "mainImg": false,
    },
    {
      "title": "The Peace Speech",
      "sub-title": "",
      "author": "President John F. Kennedy",
      "description":[
        "Washington, D.C. June 10, 1963",
        "President Anderson, members of the faculty, board of trustees, distinguished guests, my old colleague, Senator Bob Byrd, who has earned his degree through many years of attending night law school, while I am earning mine in the next 30 minutes, distinguished guests, ladies and gentlemen :",
        "It is with great pride that I participate in this ceremony of the American University, sponsored by the Methodist Church, founded by Bishop John Fletcher Hurst, and first opened by President Woodrow Wilson in 1914. This is a young and growing university, but it has already fulfilled Bishop Hurst’s enlightened hope for the study of history and public affairs in a city devoted to the making of history and the conduct of the public’s business. By sponsoring this institution of higher learning for all who wish to learn, whatever their color or their creed, the Methodists of this area and the Nation deserve the Nation’s thanks, and I commend all those who are today graduating.",
      ],
      "imgUrl": `${prefix}kennedy-dallas.jpg`,
      "link": `${prefix}kennedy-peace.html`,
      "poem": false,
      "mainImg": false,
    },
   ],
  "Current Events": [
    {
      "title": "“The Greatest Fighting Force in Human History”",
      "sub-title": "",
      "author": "William J. Astore",
      "description":[
        "In his message to the troops prior to the July 4th weekend, Secretary of Defense Lloyd Austin offered high praise indeed. “We have the greatest fighting force in human history,” he tweeted, connecting that claim to the U.S. having patriots of all colors, creeds, and backgrounds “who bravely volunteer to defend our country and our values.”",
        "As a retired Air Force lieutenant colonel from a working-class background who volunteered to serve more than four decades ago, who am I to argue with Austin? Shouldn’t I just bask in the glow of his praise for today’s troops, reflecting on my own honorable service near the end of what now must be thought of as the First Cold War?",
        "Yet I confess to having doubts. I’ve heard it all before. The hype. The hyperbole. I still remember how, soon after the 9/11 attacks, President George W. Bush boasted that this country had “the greatest force for human liberation the world has ever known.” I also remember how, in a pep talk given to U.S. troops in Afghanistan in 2010, President Barack Obama declared them “the finest fighting force that the world has ever known.” And yet, 15 years ago at TomDispatch, I was already wondering when Americans had first become so proud of, and insistent upon, declaring our military the world’s absolute best, a force beyond compare, and what that meant for a republic that once had viewed large standing armies and constant warfare as anathemas to freedom.",
      ],
      "imgUrl": `${prefix}bush_mission_accomplished.jpg`,
      "link": `${prefix}astore-greatest-fighting-force.html`,
      "poem": false,
      "mainImg": false,
    },
    {
      "title": "The Profiteers of Armageddon",
      "sub-title": "",
      "author": "William D. Hartung",
      "description":[
        "Unless you’ve been hiding under a rock for the past few months, you’re undoubtedly aware that award-winning director Christopher Nolan has released a new film about Robert Oppenheimer, known as the “father of the atomic bomb” for leading the group of scientists who created that deadly weapon as part of America’s World War II-era Manhattan Project. The film has earned widespread attention, with large numbers of people participating in what’s already become known as “Barbieheimer” by seeing Greta Gerwig’s hit film Barbie and Nolan’s three-hour-long Oppenheimer on the same day.",
        "Nolan’s film is a distinctive pop cultural phenomenon because it deals with the American use of nuclear weapons, a genuine rarity since ABC’s 1983 airing of The Day After about the consequences of nuclear war. (An earlier exception was Stanley Kubrick’s Dr. Strangelove, his satirical portrayal of the insanity of the Cold War nuclear arms race.)",
      ],
      "imgUrl": `${prefix}oppenheimer-sensation.png`,
      "link": `${prefix}hartwig-profiteering.html`,
      "poem": false,
      "mainImg": false,
    },
    {
      "title": "DEADLY IMMUNITY",
      "sub-title": "",
      "author": "Robert F. Kennedy Jr.",
      "description":[
        "In June 2000, a group of top government scientists and health officials gathered for a meeting at the isolated Simpsonwood conference center in Norcross, Ga. Convened by the Centers for Disease Control and Prevention, the meeting was held at this Methodist retreat center, nestled in wooded farmland next to the Chattahoochee River, to ensure complete secrecy. The agency had issued no public announcement of the session -- only private invitations to 52 attendees. There were high-level officials from the CDC and the Food and Drug Administration, the top vaccine specialist from the World Health Organization in Geneva, and representatives of every major vaccine manufacturer, including GlaxoSmithKline, Merck, Wyeth and Aventis Pasteur. All of the scientific data under discussion, CDC officials repeatedly reminded the participants, was strictly \"embargoed.\" There would be no making photocopies of documents, no taking papers with them when they left.",
      ],
      "imgUrl": `${prefix}rfkjr.jpg`,
      "link": `${prefix}kennedy-deadly-immunity.html`,
      "poem": false,
      "mainImg": false,
    },
    {
      "title": "AI Versus AI",
      "sub-title": "",
      "author": "Michael Klare",
      "description":[
        "A world in which machines governed by artificial intelligence (AI) systematically replace human beings in most business, industrial, and professional functions is horrifying to imagine. After all, as prominent computer scientists have been warning us, AI-governed systems are prone to critical errors and inexplicable “hallucinations,” resulting in potentially catastrophic outcomes. But there’s an even more dangerous scenario imaginable from the proliferation of super-intelligent machines: the possibility that those nonhuman entities could end up fighting one another, obliterating all human life in the process.",
        "The notion that super-intelligent computers might run amok and slaughter humans has, of course, long been a staple of popular culture. In the prophetic 1983 film “WarGames,” a supercomputer known as WOPR (for War Operation Plan Response and, not surprisingly, pronounced “whopper”) nearly provokes a catastrophic nuclear war between the United States and the Soviet Union before being disabled by a teenage hacker (played by Matthew Broderick). The “Terminator” movie franchise, beginning with the original 1984 film, similarly envisioned a self-aware supercomputer called “Skynet” that, like WOPR, was designed to control U.S. nuclear weapons but chooses instead to wipe out humanity, viewing us as a threat to its existence.",
      ],
      "imgUrl": `${prefix}ai-vs-ai.jpeg`,
      "link": `${prefix}klare-ai-ai.html`,
      "poem": false,
      "mainImg": false,
    },
   ],
  "Children's Corner": [
    {
      "title": "The Mystery of the Headless Ghost",
      "sub-title": "",
      "author": "Nicolás Gawain Smith",
      "description":[
        "This story is my dog Duque's fault. If Duque hadn't found those footprints...But it would be better to start at the beginning.",
        "It was a Monday and I was on my way to school. That day was very good in school. The English teacher was absent so we had almost an hour extra for recreation break. When I got home Duque wasn't there. I looked inside and outside, on the back porch and the front patio. Then I went out on the street to look for him. Finally I found him in the abandoned house next door barking at something. I called him but he didn't come. I whistled and he didn't come. I rolled on the floor and he didn't come. How strange, I thought. Whenever I roll on the floor he comes running and jumps on top of me. I went back home and asked my dad to let me put a leash on Duque. My dad doesn't like to put a leash on him. I went back to the abandoned house where I finally got the leash on him and brought him home.",
      ],
      "imgUrl": `${prefix}headless.webp`,
      "link": `${prefix}headless-ghost.html`,
      "poem": false,
      "mainImg": false,
    },
   ],
}
